### ISSUE TITLE
[META] Plan to get model into production

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/power_perceiver#148]
- [ ] Branch "Thursday's model"
- [ ] #147 
- [ ] #145 
- [ ] Write more tests
- [ ] Update the data loader to work in production :slightly_smiling_face:
